### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by xyproto** [mosra/magnum-examples#23]
Hello,

When compiling the triangle example with `-std=c++14 -fsanitize=address -fno-omit-frame-pointer -shared-libgcc`, the address sanitizer finds a problem upon application exit. This is using `g++ (GCC) 6.1.1 20160501`.

Here's the full output:

```
Renderer: GeForce GTX 750 Ti/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.5.0 NVIDIA 364.19
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_EXT_direct_state_access
    GL_EXT_texture_filter_anisotropic
    GL_KHR_debug
Using driver workarounds:
    amd-nv-no-forward-compatible-core-context
    no-layout-qualifiers-on-old-glsl
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits

=================================================================
==32021==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 320 byte(s) in 2 object(s) allocated from:
    #0 0x7f64bc903d58 in __interceptor_malloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:38
    #1 0x7f64b4f3c99f in glXChooseFBConfig (/usr/lib/../lib/libGLX_nvidia.so.0+0x7f99f)

SUMMARY: AddressSanitizer: 320 byte(s) leaked in 2 allocation(s).

Process returned 1 (0x1)   execution time : 4.470 s
```

When searching the web for related issues, it appears that this might be caused by not freeing the memory that is allocated by `glXChooseFBConfig`.

Thanks for creating Magnum in the first place, it looks promising!

Cheers,
Alexander F Rødseth

PS. libcorrade and libmagnum are now official Arch Linux packages. Please let me know if there should be any issues with the packaging. :)

**Comment by mosra** [comment]
Hi,

assuming you are using the defaults (thus `Platform::Sdl2Application`) -- then the leak is inside SDL2 which is not under my control and I can't do anything about it. Maybe you could report it there? Possibly relevant location: https://github.com/spurious/SDL-mirror/blob/65f383561e3becf27bab3282acb0286f8c4c3648/src/video/x11/SDL_x11opengl.c#L643

Regarding packages -- huh, that's quite unexpected :) Are they based on PKGBUILDs which I'm providing in AUR (and in `package/archlinux/*-git` in each repository)? Why `libmagnum` and not just `magnum` to be consistent with other libs like `qt`, `freetype`, `openal` etc.? The thing is that I was providing just the `*-git` packages in AUR because I have no proper release management yet and the project is not yet maintaining any binary compatibility -- only source compatibility. So currently depending on the official package may mean that it's forcing the user to recompile all the time because of ABI breaks or it's always slightly outdated.

I'm planning to do another snapshot in the next month or two (see the [tracking issue](https://github.com/mosra/magnum/issues/108)) and make it as stable as possible, that one might be worth packaging, until then it's a moving target :) The last snapshot was in May 2015 and I was not able to do another due to lack of time.

**Comment by xyproto** [comment]
I see, I'll consider reporting it to SDL2.

The packages are loosely based on the packages in AUR, yes, but using cmake + ninja and are locked to the lastest commit on git. The choice of prefixing with lib or not is a bit arbitrary, and there are existing examples of both variations. For me, the main thing was to make it clear that it was not related to the Magnum CPU (or other things named Magnum).

A release with a shorter version number would be nice, looking forward to that. :)

**Comment by mosra** [comment]
Currently the AUR packages have the `replaces`/`provides` tag set to `"magnum"` and `"corrade"`, so this would break them. I'm having `libmagnum` only in case of Debian which has consistently all libraries named with `lib` prefix, but elsewhere it's without. Both Magnum and Corrade also provide a few command-line tools so they might not be considered *just* a library.

Is it possible to change the names now? :) Otherwise I'm more than happy.

**Comment by xyproto** [comment]
OK, will see if I can change the name back to just "magnum" and "corrade" in a couple of days.

**Comment by mosra** [comment]
@xyproto saw them renamed, thanks! :)
