### ISSUE TITLE
example cubemap does work on Intel HD Graphics 530

### ISSUE THREAD

**Issue by hunt978** [mosra/magnum-examples#55]
cannot load the cubemap texture, got black screen, while executed successfully on nvidia cards.

Renderer: Intel(R) HD Graphics 530 by Intel
OpenGL version: 4.5.0 - Build 23.20.16.4973

Magnum console gave no warning/error message.

**Comment by mosra** [comment]
Oh well. Intel drivers on Windows are always full of surprises :/ For the record, I'm not getting such issue on Intel Mesa drivers on Linux. 

What's the full engine log (including extensions and workaround used)? Maybe disabling some of these could make it work.

**Comment by mosra** [comment]
I was plowing through all the bugs related to Intel Windows drivers and this was one of them, cube maps in particular were *extremely broken*. I managed to reproduce and two new workarounds are in place since mosra/magnum@580a3c55535ac38c6974f4d09845301ecbe25af9 and mosra/magnum@f9c6deae6376d4fc2885740015dcb2077e6a3969, which are fixing this issue. (Apart from these, there's [6 other workarounds](https://doc.magnum.graphics/magnum/opengl-workarounds.html) "fixing" other Intel bugs.)
