### ISSUE TITLE
All examples only show black screen

### ISSUE THREAD

**Issue by yurivict** [mosra/magnum-examples#56]
They print this:
```
$ /usr/local/bin/magnum-primitives 
Platform: can't get Xft.dpi property for virtual DPI scaling, falling back to physical DPI
Renderer: GeForce GT 610/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: OpenGL ES 3.2 NVIDIA 390.87
Using optional features:
    GL_EXT_robustness
    GL_EXT_texture_filter_anisotropic

$ /usr/local/bin/magnum-triangle
Platform: can't get Xft.dpi property for virtual DPI scaling, falling back to physical DPI
Renderer: GeForce GT 610/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: OpenGL ES 3.2 NVIDIA 390.87
Using optional features:
    GL_EXT_robustness
    GL_EXT_texture_filter_anisotropic
```

**Comment by mosra** [comment]
What platform is this? Is the black screen really black (`#000000`) or showing *at least* the default clear color (`#1f1f1f`)? Is there any difference if you build for desktop OpenGL instead of ES? Is this a platform with X11? Or Wayland? 

I have to admit there are some corner cases (especially involving desktops using EGL instead of GLX and non-X11 Linux/BSD platforms) where function pointer loading is tested less than ideally, and thus for example the driver is just executing some dummy functions instead of actually making the GPU draw stuff. Are you able to use ApiTrace or Renderdoc there to debug things further?

**Comment by yurivict** [comment]
> Is the black screen really black (`#000000`) or showing at least the default clear color (`#1f1f1f`)?

The color is (`#1f1f1f`).

> Is there any difference if you build for desktop OpenGL instead of ES?

Removing ```TARGET_GLES``` in ```magnum``` config made the problem to go away.

> Is this a platform with X11? Or Wayland?

X11, FreeBSD 11.2 amd64

**Comment by mosra** [comment]
Hmm. Not sure how to continue here. Testing here with `TARGET_GLES` enabled, both of these do exactly what told:

```shell-session
$ ./src/triangle/magnum-triangle 
Renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2)  by Intel Open Source Technology Center
OpenGL version: OpenGL ES 3.2 Mesa 18.3.3
Using optional features:
    GL_EXT_multi_draw_arrays
    GL_EXT_robustness
    GL_EXT_texture_filter_anisotropic
^C
$ DRI_PRIME=1 ./src/triangle/magnum-triangle 
Renderer: AMD VEGAM (DRM 3.27.0, 4.20.10-arch1-1-ARCH, LLVM 7.0.1) by X.Org
OpenGL version: OpenGL ES 3.2 Mesa 18.3.3
Using optional features:
    GL_EXT_multi_draw_arrays
    GL_EXT_robustness
    GL_EXT_texture_filter_anisotropic

```

IIRC from the time when I had a NVidia, this worked well, unfortunately I don't have a machine with NV anymore. 

The magnum repository has a big suite of tests for the OpenGL backed (enabled using `BUILD_TESTS` and `BUILD_GL_TESTS`). Could you run the most essential ones on the GLES build and tell me the output?

```sh
cd build
cmake -DBUILD_TESTS=ON -DBUILD_GL_TESTS=ON .
cmake --build .
ctest -V -R (GLMeshGLTest|GLBufferGLTest|GLAbstractShaderProgramGLTest)
```

**Comment by mosra** [comment]
Closing due to a lack of activity.
