### ISSUE TITLE
MeshData.h include no longer valid?

### ISSUE THREAD

**Issue by leventt** [mosra/magnum-examples#78]
I am following this example:
https://doc.magnum.graphics/magnum/examples-primitives.html

I did set myself up with vcpkg...

MeshData.h doesn't seem to be valid and there are ...2D and ...3D suffixes to that header now.

Is this a known issue?

**Comment by leventt** [comment]
Installing latest master fixed this \o/
https://doc.magnum.graphics/magnum/building.html#building-packages-vcpkg

Thanks for the great documentation!

**Comment by mosra** [comment]
Hi, sorry about that -- you had the bad luck of trying out the project right after I did a rather massive breaking change. This doesn't happen often, but here I had to rethink some rather limiting design decisions from the past decade (see mosra/magnum#371) :)

Just a heads up, there's another minor breakage caused by mosra/magnum@32d49db4028eccde901869e480bf1c9c275ccbca. All docs refer to the new API, so you might want to pull latest master again.

**Comment by leventt** [comment]
Thanks for the heads up! I decided to work with the latest release which worked great and I was surprised how easy it was for emscripten-wasm compiling. I am not too sure if I could use it with ONNX.js however, which seems to be one of the things I will try to integrate to my project. I will perhaps open another discussion for this in the future but how to interop between a js library and cxx wasn't obvious to me.

Cheerrs!

**Comment by mosra** [comment]
Btw., feel free to join https://gitter.im/mosra/magnum (you can log in with your GitHub account), the response time there is generally much shorter :)
