### ISSUE TITLE
Viewer example closes at startup...

### ISSUE THREAD

**Issue by jquiver** [mosra/magnum-examples#94]
Hi,
I can't get the viewer example to start on Windows, VS2019 
When executing the   .parse(argc, argv)  the application exists with exit(1) without printing anything.
The exact part of the code where this is happening is here (checked with the debugger)

```
   Utility::Arguments args;
    args.addArgument("file").setHelp("file", "file to load")
        .addOption("importer", "AnySceneImporter").setHelp("importer", "importer plugin to use")
        .addSkippedPrefix("magnum", "engine-specific options")
        .setGlobalHelp("Displays a 3D scene file provided on command line.")
        .parse(arguments.argc, arguments.argv); 

```

An I missing some arguments when executing the application, if yes how to pass them?
Thansk!

Jquiver

**Comment by jquiver** [comment]
solved, I was using the wrong version of magnum.
Great project, keep up the good work.

**Comment by mosra** [comment]
Hi,

just for the record, it should print something like

```
Missing command-line argument file
Usage:
  magnum-viewer [--magnum-...] [-h|--help] [--importer IMPORTER] [--] file
```

and you're expected to run it as `magnum-viewer somefile.obj`. However, assuming you're running from within VS, the "missing output" is probably due to https://github.com/mosra/corrade/issues/79 -- the output is printed to standard error, but VS for some reason ignores that and displays only what was passed to `OutputDebugString()`. This is something I still need to fix.
